schema = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 3

[[blocks]]
type = "prompt"
alignment = "left"

[[blocks.segments]]
type = "os"
style = "plain"
template = "{{.Icon}}"
foreground = "#26C6DA"
[blocks.segments.properties]
cache_duration = "none"
macos = "mac"

[[blocks.segments]]
type = "session"
style = "plain"
template = " {{ .UserName }}: "
foreground = "#26C6DA"
[blocks.segments.properties]
cache_duration = "none"

[[blocks.segments]]
type = "path"
style = "plain"
template = "{{ .Path }} "
foreground = "lightGreen"
[blocks.segments.properties]
cache_duration = "none"
style = "folder"

[[blocks.segments]]
type = "git"
style = "plain"
template = "{{ .UpstreamIcon }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} "
foreground = "#f1502f"
[blocks.segments.properties]
cache_duration = "none"
branch_icon = ""
fetch_stash_count = true
background_templates = [
    "{{ if or (.Working.Changed) (.Staging.Changed) }}#FFEB3B{{ end }}",
    "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#FFCC80{{ end }}",
    "{{ if gt .Ahead 0 }}#B388FF{{ end }}",
    "{{ if gt .Behind 0 }}#B388FB{{ end }}",
]

[[blocks.segments]]
type = "rust"
style = "powerline"
template = "[ {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}] "
foreground = "#994d00"
[blocks.segments.properties]
cache_duration = "none"

[[blocks.segments]]
type = "python"
style = "powerline"
template = "[ {{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }} {{ end }}{{ .Full }}{{ end }}] "
foreground = "#906cff"
[blocks.segments.properties]
cache_duration = "none"

[[blocks.segments]]
type = "go"
style = "powerline"
template = "[ {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}] "
foreground = "#7FD5EA"
[blocks.segments.properties]
cache_duration = "none"

[[blocks.segments]]
type = "node"
style = "powerline"
template = "[ {{ if .PackageManagerIcon }}{{ .PackageManagerIcon }} {{ end }}{{ .Full }}] "
foreground = "#76b367"
[blocks.segments.properties]
cache_duration = "none"

[[blocks.segments]]
type = "ruby"
style = "powerline"
template = "[{{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}] "
foreground = "#f44336"
[blocks.segments.properties]
cache_duration = "none"

[[blocks.segments]]
type = "java"
style = "powerline"
template = "[ {{ if .Error }}{{ .Error }}{{ else }}{{ .Full }}{{ end }}] "
foreground = "#ea2d2e"
[blocks.segments.properties]
cache_duration = "none"

[[blocks.segments]]
type = "status"
style = "plain"
template = "{{if .Error }}󰋔{{ else }}{{ end }}"
foreground = "#66ff66"
foreground_templates = ["{{ if .Error }}#e91e63{{ end }}"]
[blocks.segments.properties]
cache_duration = "none"
always_enabled = true

[[blocks.segments]]
type = "text"
style = "plain"
template = "\n ↳"
foreground = "#FFD54F"
[blocks.segments.properties]
cache_duration = "none"
